# Mini Projek

## Import Package

In [97]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import os 

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import KMeans

## Data Overview

In [98]:
data_path = os.path.join("Mini Projek", "lead_scoring.csv")
print(data_path)

Mini Projek\lead_scoring.csv

In [99]:
data = pd.read_csv(data_path)

In [100]:
data.shape

(9240, 37)

In [101]:
data.head()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Jakarta,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Jakarta,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Jakarta,02.Medium,01.High,15.0,18.0,No,No,Modified

In [102]:
data.tail()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Potential Lead,Jakarta,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,Potential Lead,Jakarta,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,Potential Lead,Jakarta,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [103]:
data.sample(5, random_state=91)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
6936,2154ccbd-41f9-46f0-9edb-308cde9fc52d,596447,Landing Page Submission,Google,No,No,0,2.0,238,2.0,...,No,Select,Jakarta,NaN,NaN,NaN,NaN,No,No,Modified
2140,5f05a482-8fb5-4fe8-aca3-0f7b9d794178,639211,Lead Add Form,Reference,No,No,1,0.0,0,0.0,...,No,Potential Lead,Bodetabek,02.Medium,02.Medium,14.0,16.0,No,No,Modified
4377,2be87f90-5931-49dc-bb87-54d8452cb693,617791,Landing Page Submission,Google,No,No,0,5.0,582,5.0,...,No,Select,Jakarta,NaN,NaN,NaN,NaN,No,No,SMS Sent
5208,65e13a16-f5c0-49a1-8187-a4795a5941fb,609879,Landing Page Submission,Direct Traffic,No,No,0,3.0,1686,3.0,...,No,Select,Bodetabek,NaN,NaN,NaN,NaN,No,Yes,Email Opened
1041,0adb324b-c2a3-4880-a928-6e1589914ab4,649091,Landing Page Submission,Google,No,No,0,7.0,1541,3.5,...,No,NaN,Cities in Banten & Jawa Barat,02.Medium,01.High,14.0,17.0,No,Yes,Email Opened

In [104]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Prospect ID                                     9240 non-null   object
 1   Lead Number                                     9240 non-null   int64
 2   Lead Origin                                     9240 non-null   object
 3   Lead Source                                     9204 non-null   object
 4   Do Not Email                                    9240 non-null   object
 5   Do Not Call                                     9240 non-null   object
 6   Converted                                       9240 non-null   int64
 7   TotalVisits                                     9103 non-null   float64
 8   Total Time Spent on Website                     9240 non-null   int64
 9   Page Views Per Visit                            9103 non-null   float64
 10  Last Activity                                   9137 non-null   object
 11  Country                                         6779 non-null   object
 12  Specialization                                  7802 non-null   object
 13  How did you hear about Madugital                7033 non-null   object
 14  What is your current occupation                 6550 non-null   object
 15  What matters most to you in choosing a product  6531 non-null   object
 16  Search                                          9240 non-null   object
 17  Magazine                                        9240 non-null   object
 18  Newspaper Article                               9240 non-null   object
 19  Madugital Telegram                              9240 non-null   object
 20  Newspaper                                       9240 non-null   object
 21  Digital Advertisement                           9240 non-null   object
 22  Through Recommendations                         9240 non-null   object
 23  Receive More Updates About Our Products         9240 non-null   object
 24  Tags                                            5887 non-null   object
 25  Lead Quality                                    4473 non-null   object
 26  Update me on Supply Chain Content               9240 non-null   object
 27  Get updates on DM Content                       9240 non-null   object
 28  Lead Profile                                    6531 non-null   object
 29  City                                            7820 non-null   object
 30  Asymmetrique Activity Index                     5022 non-null   object
 31  Asymmetrique Profile Index                      5022 non-null   object
 32  Asymmetrique Activity Score                     5022 non-null   float64
 33  Asymmetrique Profile Score                      5022 non-null   float64
 34  I agree to pay the amount through cheque        9240 non-null   object
 35  A free copy of Mastering The Interview          9240 non-null   object
 36  Last Notable Activity                           9240 non-null   object
dtypes: float64(4), int64(3), object(30)
memory usage: 2.6+ MB

## Data Quality Check

In [105]:
data["Lead Source"].unique()

array(['Olark Chat', 'Organic Search', 'Direct Traffic', 'Google',
       'Referral Sites', 'Welingak Website', 'Reference', 'google',
       'Facebook', nan, 'blog', 'Pay per Click Ads', 'bing',
       'Social Media', 'WeLearn', 'Click2call', 'Live Chat',
       'welearnblog_Home', 'youtubechannel', 'testone', 'Press_Release',
       'NC_EDM'], dtype=object)

In [106]:
data["TotalVisits"].unique()

array([  0.,   5.,   2.,   1.,   4.,   8.,  11.,   6.,   3.,   7.,  13.,
        17.,  nan,   9.,  12.,  10.,  16.,  14.,  21.,  15.,  22.,  19.,
        18.,  20.,  43.,  30.,  23.,  55., 141.,  25.,  27.,  29.,  24.,
        28.,  26.,  74.,  41.,  54., 115., 251.,  32.,  42.])

In [107]:
data.describe(include='O') #untuk melihat pesebaran data categorik

,Prospect ID,Lead Origin,Lead Source,Do Not Email,Do Not Call,Last Activity,Country,Specialization,How did you hear about Madugital,What is your current occupation,...,Lead Quality,Update me on Supply Chain Content,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
count,9240,9240,9204,9240,9240,9137,6779,7802,7033,6550,...,4473,9240,9240,6531,7820,5022,5022,9240,9240,9240
unique,9240,5,21,2,2,17,38,19,10,6,...,5,1,1,6,7,3,3,1,2,16
top,7927b2df-8bba-4d29-b9a2-b6e0beafe620,Landing Page Submission,Google,No,No,Email Opened,Indonesia,Select,Select,Unemployed,...,Might be,No,No,Select,Jakarta,02.Medium,02.Medium,No,No,Modified
freq,1,4886,2868,8506,9238,3437,6492,1942,5043,5600,...,1560,9240,9240,4146,3222,3839,2788,9240,6352,3407

In [108]:
data.describe() #untuk melihat pesebaran data numerik

,Lead Number,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score
count,9240.000000,9240.000000,9103.000000,9240.000000,9103.000000,5022.000000,5022.000000
mean,617188.435606,0.385390,3.445238,487.698268,2.362820,14.306252,16.344883
std,23405.995698,0.486714,4.854853,548.021466,2.161418,1.386694,1.811395
min,579533.000000,0.000000,0.000000,0.000000,0.000000,7.000000,11.000000
25%,596484.500000,0.000000,1.000000,12.000000,1.000000,14.000000,15.000000
50%,615479.000000,0.000000,3.000000,248.000000,2.000000,14.000000,16.000000
75%,637387.250000,1.000000,5.000000,936.000000,3.000000,15.000000,18.000000
max,660737.000000,1.000000,251.000000,2272.000000,55.000000,18.000000,20.000000

In [109]:
data.isnull().sum() #melihat value yang kosong

Prospect ID                                          0
Lead Number                                          0
Lead Origin                                          0
Lead Source                                         36
Do Not Email                                         0
Do Not Call                                          0
Converted                                            0
TotalVisits                                        137
Total Time Spent on Website                          0
Page Views Per Visit                               137
Last Activity                                      103
Country                                           2461
Specialization                                    1438
How did you hear about Madugital                  2207
What is your current occupation                   2690
What matters most to you in choosing a product    2709
Search                                               0
Magazine                                             0
Newspaper Article                                    0
Madugital Telegram                                   0
Newspaper                                            0
Digital Advertisement                                0
Through Recommendations                              0
Receive More Updates About Our Products              0
Tags                                              3353
Lead Quality                                      4767
Update me on Supply Chain Content                    0
Get updates on DM Content                            0
Lead Profile                                      2709
City                                              1420
Asymmetrique Activity Index                       4218
Asymmetrique Profile Index                        4218
Asymmetrique Activity Score                       4218
Asymmetrique Profile Score                        4218
I agree to pay the amount through cheque             0
A free copy of Mastering The Interview               0
Last Notable Activity                                0
dtype: int64

In [110]:
#melihat persentase baris yang kosong dari keseluruhan 
#(jika persentasi lebih dari 60% lebih baik di dropna saja, di bawah 60% masih bisa di fillna)
data.isna().mean()*100

Prospect ID                                        0.000000
Lead Number                                        0.000000
Lead Origin                                        0.000000
Lead Source                                        0.389610
Do Not Email                                       0.000000
Do Not Call                                        0.000000
Converted                                          0.000000
TotalVisits                                        1.482684
Total Time Spent on Website                        0.000000
Page Views Per Visit                               1.482684
Last Activity                                      1.114719
Country                                           26.634199
Specialization                                    15.562771
How did you hear about Madugital                  23.885281
What is your current occupation                   29.112554
What matters most to you in choosing a product    29.318182
Search                                             0.000000
Magazine                                           0.000000
Newspaper Article                                  0.000000
Madugital Telegram                                 0.000000
Newspaper                                          0.000000
Digital Advertisement                              0.000000
Through Recommendations                            0.000000
Receive More Updates About Our Products            0.000000
Tags                                              36.287879
Lead Quality                                      51.590909
Update me on Supply Chain Content                  0.000000
Get updates on DM Content                          0.000000
Lead Profile                                      29.318182
City                                              15.367965
Asymmetrique Activity Index                       45.649351
Asymmetrique Profile Index                        45.649351
Asymmetrique Activity Score                       45.649351
Asymmetrique Profile Score                        45.649351
I agree to pay the amount through cheque           0.000000
A free copy of Mastering The Interview             0.000000
Last Notable Activity                              0.000000
dtype: float64

In [111]:
data_dropped = data.dropna()
data_dropped.isnull().sum()

Prospect ID                                       0
Lead Number                                       0
Lead Origin                                       0
Lead Source                                       0
Do Not Email                                      0
Do Not Call                                       0
Converted                                         0
TotalVisits                                       0
Total Time Spent on Website                       0
Page Views Per Visit                              0
Last Activity                                     0
Country                                           0
Specialization                                    0
How did you hear about Madugital                  0
What is your current occupation                   0
What matters most to you in choosing a product    0
Search                                            0
Magazine                                          0
Newspaper Article                                 0
Madugital Telegram                                0
Newspaper                                         0
Digital Advertisement                             0
Through Recommendations                           0
Receive More Updates About Our Products           0
Tags                                              0
Lead Quality                                      0
Update me on Supply Chain Content                 0
Get updates on DM Content                         0
Lead Profile                                      0
City                                              0
Asymmetrique Activity Index                       0
Asymmetrique Profile Index                        0
Asymmetrique Activity Score                       0
Asymmetrique Profile Score                        0
I agree to pay the amount through cheque          0
A free copy of Mastering The Interview            0
Last Notable Activity                             0
dtype: int64

In [112]:
data.shape, data_dropped.shape

((9240, 37), (1943, 37))

In [113]:
data_dropped = data.drop(columns=['Lead Quality'], axis =1)
data_dropped.isnull().sum()

Prospect ID                                          0
Lead Number                                          0
Lead Origin                                          0
Lead Source                                         36
Do Not Email                                         0
Do Not Call                                          0
Converted                                            0
TotalVisits                                        137
Total Time Spent on Website                          0
Page Views Per Visit                               137
Last Activity                                      103
Country                                           2461
Specialization                                    1438
How did you hear about Madugital                  2207
What is your current occupation                   2690
What matters most to you in choosing a product    2709
Search                                               0
Magazine                                             0
Newspaper Article                                    0
Madugital Telegram                                   0
Newspaper                                            0
Digital Advertisement                                0
Through Recommendations                              0
Receive More Updates About Our Products              0
Tags                                              3353
Update me on Supply Chain Content                    0
Get updates on DM Content                            0
Lead Profile                                      2709
City                                              1420
Asymmetrique Activity Index                       4218
Asymmetrique Profile Index                        4218
Asymmetrique Activity Score                       4218
Asymmetrique Profile Score                        4218
I agree to pay the amount through cheque             0
A free copy of Mastering The Interview               0
Last Notable Activity                                0
dtype: int64

In [114]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Prospect ID                                     9240 non-null   object
 1   Lead Number                                     9240 non-null   int64
 2   Lead Origin                                     9240 non-null   object
 3   Lead Source                                     9204 non-null   object
 4   Do Not Email                                    9240 non-null   object
 5   Do Not Call                                     9240 non-null   object
 6   Converted                                       9240 non-null   int64
 7   TotalVisits                                     9103 non-null   float64
 8   Total Time Spent on Website                     9240 non-null   int64
 9   Page Views Per Visit                            9103 non-null   float64
 10  Last Activity                                   9137 non-null   object
 11  Country                                         6779 non-null   object
 12  Specialization                                  7802 non-null   object
 13  How did you hear about Madugital                7033 non-null   object
 14  What is your current occupation                 6550 non-null   object
 15  What matters most to you in choosing a product  6531 non-null   object
 16  Search                                          9240 non-null   object
 17  Magazine                                        9240 non-null   object
 18  Newspaper Article                               9240 non-null   object
 19  Madugital Telegram                              9240 non-null   object
 20  Newspaper                                       9240 non-null   object
 21  Digital Advertisement                           9240 non-null   object
 22  Through Recommendations                         9240 non-null   object
 23  Receive More Updates About Our Products         9240 non-null   object
 24  Tags                                            5887 non-null   object
 25  Lead Quality                                    4473 non-null   object
 26  Update me on Supply Chain Content               9240 non-null   object
 27  Get updates on DM Content                       9240 non-null   object
 28  Lead Profile                                    6531 non-null   object
 29  City                                            7820 non-null   object
 30  Asymmetrique Activity Index                     5022 non-null   object
 31  Asymmetrique Profile Index                      5022 non-null   object
 32  Asymmetrique Activity Score                     5022 non-null   float64
 33  Asymmetrique Profile Score                      5022 non-null   float64
 34  I agree to pay the amount through cheque        9240 non-null   object
 35  A free copy of Mastering The Interview          9240 non-null   object
 36  Last Notable Activity                           9240 non-null   object
dtypes: float64(4), int64(3), object(30)
memory usage: 2.6+ MB

In [115]:
data_dropped.loc[data_dropped['Lead Source'].isnull()]

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
836,b2dfb7a5-814d-465b-816e-63d6b3a863ca,651660,Lead Add Form,NaN,Yes,No,1,NaN,1378,NaN,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,Modified
1569,1c87e9fd-c675-468e-9653-2cc968f077f2,643899,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent
1746,215e9984-818a-42ff-ba1c-667ce73199a5,642394,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified
2020,06f5b430-a45a-4de2-9aca-e13ee0a43589,640115,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
2025,e7524e35-923e-4c9f-800d-b18e1a6c5e3b,640081,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
2152,e54f76cc-2436-451c-8a29-fcd32ed7bed4,639134,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent
2346,c309cc6d-204f-4ac0-a766-7d326bd01218,637125,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent
2544,175611de-436d-11e6-b61b-22000aa8e760,635028,Lead Import,NaN,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,15.0,No,No,Email Opened
2601,bbe44370-ea5a-4e46-99d9-d32cfbd32199,634618,Quick Add Form,NaN,Yes,No,1,NaN,2217,NaN,...,No,Select,Other Metro Cities,02.Medium,02.Medium,14.0,13.0,No,No,Modified
2676,bcfdd00e-99d2-4be1-b09b-a6260a63dade,633945,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Potential Lead,Cities in Banten & Jawa Barat,NaN,NaN,NaN,NaN,No,No,SMS Sent
3028,6238e5d6-2708-4d78-8180-82fd603c8a22,630801,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
3266,1081fb9a-3309-46b6-a890-74de644e05c8,628685,Landing Page Submission,NaN,No,No,1,2.0,9,2.0,...,No,Select,Jakarta,NaN,NaN,NaN,NaN,No,No,SMS Sent
3268,4a959213-0cef-4b5f-bab0-9198557b5d8f,628666,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
3928,829524dc-e9c8-4f6d-8947-591e1c1746b0,622403,Lead Add Form,NaN,Yes,No,0,NaN,44,NaN,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified
3945,f7aa46f0-2fe2-459a-8235-66e132910778,622280,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
4406,348bc75a-dbb6-4605-8d4a-fb02da9d48e2,617520,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
4409,19fd3dc0-dd17-4490-8d10-364de953b7e7,617495,Lead Add Form,NaN,No,No,0,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Email Opened
4605,393a4d46-8f73-43a4-966a-43d22773ba68,615643,Lead Add Form,NaN,Yes,No,0,NaN,156,NaN,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified
4653,abd3afd7-7f13-4111-9710-d84fe67c8888,615069,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
4804,53ef2d0f-c083-4629-a434-e0693f5fdf69,613917,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Email Opened
4831,7e508a13-6f61-4e5d-834d-52573fb85b33,613660,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified
4843,99e07a6e-5071-4211-bef3-f3b322effe6a,613583,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
5253,12a7df19-b6dd-4e53-abd7-3d869069189a,609475,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
5621,1f442c0a-4c91-4ba7-858a-589e78ade2bb,606860,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Potential Lead,Bodetabek,NaN,NaN,NaN,NaN,No,No,SMS Sent
5840,08b0957c-8296-4e8e-bc4a-1c688f1a1f7e,605099,Lead Add Form,NaN,No,No,1,NaN,506,NaN,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified
5960,7ec55e1d-0868-4812-99ed-474f03ed35e8,604134,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
6124,58690710-0a0b-4209-a64d-46317163c4b8,602759,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent
7302,5e748f60-2b1c-4793-a143-6b097df3aa88,593400,Lead Add Form,NaN,Yes,No,0,NaN,926,NaN,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified
7306,1f691d7c-ccdb-467c-9302-30e8af12688a,593374,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent
7525,32fc4033-a135-422e-829f-603355119cba,591848,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Potential Lead,Jakarta,02.Medium,02.Medium,15.0,16.0,No,No,Unsubscribed
7847,66099c96-232e-4156-97c3-9040650798db,589591,Lead Add Form,NaN,No,No,0,NaN,289,NaN,...,No,Select,Select,02.Medium,02.Medium,13.0,16.0,No,No,Modified
8092,ae60c38c-6869-44a9-8ba7-43a77bc1e845,587995,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,Email Opened
8118,80f5897b-9092-40f4-86e3-029d988ba27b,587880,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Potential Lead,Select,02.Medium,01.High,14.0,17.0,No,No,SMS Sent
8276,3e03ad49-784e-430a-908d-abb7b4e9dfc7,586678,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified
8490,95832f2b-d5b1-47c7-8be4-4523a358ae25,584932,Lead Add Form,NaN,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,13.0,16.0,No,No,SMS Sent
9160,96467c35-9981-463e-be86-0028408d8e53,580221,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,No,Potential Lead,Select,02.Medium,01.High,14.0,17.0,No,No,Unsubscribed

In [116]:
data_dropped['Lead Source_filled'] = data_dropped['Lead Source'].fillna('Missing')

In [117]:
data_dropped.loc[data_dropped['Lead Source'].isnull()]

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity,Lead Source_filled
836,b2dfb7a5-814d-465b-816e-63d6b3a863ca,651660,Lead Add Form,NaN,Yes,No,1,NaN,1378,NaN,...,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,Modified,Missing
1569,1c87e9fd-c675-468e-9653-2cc968f077f2,643899,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent,Missing
1746,215e9984-818a-42ff-ba1c-667ce73199a5,642394,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified,Missing
2020,06f5b430-a45a-4de2-9aca-e13ee0a43589,640115,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent,Missing
2025,e7524e35-923e-4c9f-800d-b18e1a6c5e3b,640081,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent,Missing
2152,e54f76cc-2436-451c-8a29-fcd32ed7bed4,639134,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent,Missing
2346,c309cc6d-204f-4ac0-a766-7d326bd01218,637125,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent,Missing
2544,175611de-436d-11e6-b61b-22000aa8e760,635028,Lead Import,NaN,No,No,0,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,14.0,15.0,No,No,Email Opened,Missing
2601,bbe44370-ea5a-4e46-99d9-d32cfbd32199,634618,Quick Add Form,NaN,Yes,No,1,NaN,2217,NaN,...,Select,Other Metro Cities,02.Medium,02.Medium,14.0,13.0,No,No,Modified,Missing
2676,bcfdd00e-99d2-4be1-b09b-a6260a63dade,633945,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Potential Lead,Cities in Banten & Jawa Barat,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
3028,6238e5d6-2708-4d78-8180-82fd603c8a22,630801,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
3266,1081fb9a-3309-46b6-a890-74de644e05c8,628685,Landing Page Submission,NaN,No,No,1,2.0,9,2.0,...,Select,Jakarta,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
3268,4a959213-0cef-4b5f-bab0-9198557b5d8f,628666,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
3928,829524dc-e9c8-4f6d-8947-591e1c1746b0,622403,Lead Add Form,NaN,Yes,No,0,NaN,44,NaN,...,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified,Missing
3945,f7aa46f0-2fe2-459a-8235-66e132910778,622280,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
4406,348bc75a-dbb6-4605-8d4a-fb02da9d48e2,617520,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
4409,19fd3dc0-dd17-4490-8d10-364de953b7e7,617495,Lead Add Form,NaN,No,No,0,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,Email Opened,Missing
4605,393a4d46-8f73-43a4-966a-43d22773ba68,615643,Lead Add Form,NaN,Yes,No,0,NaN,156,NaN,...,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified,Missing
4653,abd3afd7-7f13-4111-9710-d84fe67c8888,615069,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
4804,53ef2d0f-c083-4629-a434-e0693f5fdf69,613917,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,Email Opened,Missing
4831,7e508a13-6f61-4e5d-834d-52573fb85b33,613660,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified,Missing
4843,99e07a6e-5071-4211-bef3-f3b322effe6a,613583,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
5253,12a7df19-b6dd-4e53-abd7-3d869069189a,609475,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
5621,1f442c0a-4c91-4ba7-858a-589e78ade2bb,606860,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Potential Lead,Bodetabek,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
5840,08b0957c-8296-4e8e-bc4a-1c688f1a1f7e,605099,Lead Add Form,NaN,No,No,1,NaN,506,NaN,...,Select,Select,NaN,NaN,NaN,NaN,No,No,Modified,Missing
5960,7ec55e1d-0868-4812-99ed-474f03ed35e8,604134,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
6124,58690710-0a0b-4209-a64d-46317163c4b8,602759,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,NaN,NaN,NaN,NaN,No,No,SMS Sent,Missing
7302,5e748f60-2b1c-4793-a143-6b097df3aa88,593400,Lead Add Form,NaN,Yes,No,0,NaN,926,NaN,...,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified,Missing
7306,1f691d7c-ccdb-467c-9302-30e8af12688a,593374,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,SMS Sent,Missing
7525,32fc4033-a135-422e-829f-603355119cba,591848,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,Potential Lead,Jakarta,02.Medium,02.Medium,15.0,16.0,No,No,Unsubscribed,Missing
7847,66099c96-232e-4156-97c3-9040650798db,589591,Lead Add Form,NaN,No,No,0,NaN,289,NaN,...,Select,Select,02.Medium,02.Medium,13.0,16.0,No,No,Modified,Missing
8092,ae60c38c-6869-44a9-8ba7-43a77bc1e845,587995,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,14.0,16.0,No,No,Email Opened,Missing
8118,80f5897b-9092-40f4-86e3-029d988ba27b,587880,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Potential Lead,Select,02.Medium,01.High,14.0,17.0,No,No,SMS Sent,Missing
8276,3e03ad49-784e-430a-908d-abb7b4e9dfc7,586678,Lead Add Form,NaN,No,No,1,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,15.0,16.0,No,No,Modified,Missing
8490,95832f2b-d5b1-47c7-8be4-4523a358ae25,584932,Lead Add Form,NaN,No,No,0,0.0,0,0.0,...,Select,Select,02.Medium,02.Medium,13.0,16.0,No,No,SMS Sent,Missing
9160,96467c35-9981-463e-be86-0028408d8e53,580221,Lead Add Form,NaN,Yes,No,1,0.0,0,0.0,...,Potential Lead,Select,02.Medium,01.High,14.0,17.0,No,No,Unsubscribed,Missing

In [118]:
data_dropped.shape

(9240, 37)

In [119]:
#numerikal
data_dropped['TotalVisits'] = data_dropped['TotalVisits'].fillna(method='ffill')
data_dropped['Page Views Per Visit'] = data_dropped['Page Views Per Visit'].fillna(method='ffill')
data_dropped['Asymmetrique Activity Score']=data_dropped['Asymmetrique Activity Score'].fillna(method='ffill')
data_dropped['Asymmetrique Profile Score']=data_dropped['Asymmetrique Profile Score'].fillna(method='ffill')

#categorik
data_dropped['Lead Source']=data_dropped['Lead Source'].fillna(data_dropped['Lead Source'].value_counts().idxmax())
data_dropped['Last Activity']=data_dropped['Last Activity'].fillna(data_dropped['Last Activity'].value_counts().idxmax())
data_dropped['Country']=data_dropped['Country'].fillna(data_dropped['Country'].value_counts().idxmax())
data_dropped['Specialization']=data_dropped['Specialization'].fillna(data_dropped['Specialization'].value_counts().idxmax())
data_dropped['How did you hear about Madugital'] = data_dropped['How did you hear about Madugital'].fillna(data_dropped['How did you hear about Madugital'].value_counts().idxmax())
data_dropped['What is your current occupation'] = data_dropped['What is your current occupation'].fillna(data_dropped['What is your current occupation'].value_counts().idxmax())
data_dropped['What matters most to you in choosing a product'] = data_dropped['What matters most to you in choosing a product'].fillna(data_dropped['What matters most to you in choosing a product'].value_counts().idxmax())
data_dropped['Tags']=data_dropped['Tags'].fillna(data_dropped['Tags'].value_counts().idxmax())
data_dropped['Lead Profile']=data_dropped['Lead Profile'].fillna(data_dropped['Lead Profile'].value_counts().idxmax())
data_dropped['City']=data_dropped['City'].fillna(data_dropped['City'].value_counts().idxmax())
data_dropped['Asymmetrique Activity Index']=data_dropped['Asymmetrique Activity Index'].fillna(data_dropped['Asymmetrique Activity Index'].value_counts().idxmax())
data_dropped['Asymmetrique Profile Index']=data_dropped['Asymmetrique Profile Index'].fillna(data_dropped['Asymmetrique Profile Index'].value_counts().idxmax())

In [120]:
data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Prospect ID                                     9240 non-null   object
 1   Lead Number                                     9240 non-null   int64
 2   Lead Origin                                     9240 non-null   object
 3   Lead Source                                     9240 non-null   object
 4   Do Not Email                                    9240 non-null   object
 5   Do Not Call                                     9240 non-null   object
 6   Converted                                       9240 non-null   int64
 7   TotalVisits                                     9240 non-null   float64
 8   Total Time Spent on Website                     9240 non-null   int64
 9   Page Views Per Visit                            9240 non-null   float64
 10  Last Activity                                   9240 non-null   object
 11  Country                                         9240 non-null   object
 12  Specialization                                  9240 non-null   object
 13  How did you hear about Madugital                9240 non-null   object
 14  What is your current occupation                 9240 non-null   object
 15  What matters most to you in choosing a product  9240 non-null   object
 16  Search                                          9240 non-null   object
 17  Magazine                                        9240 non-null   object
 18  Newspaper Article                               9240 non-null   object
 19  Madugital Telegram                              9240 non-null   object
 20  Newspaper                                       9240 non-null   object
 21  Digital Advertisement                           9240 non-null   object
 22  Through Recommendations                         9240 non-null   object
 23  Receive More Updates About Our Products         9240 non-null   object
 24  Tags                                            9240 non-null   object
 25  Update me on Supply Chain Content               9240 non-null   object
 26  Get updates on DM Content                       9240 non-null   object
 27  Lead Profile                                    9240 non-null   object
 28  City                                            9240 non-null   object
 29  Asymmetrique Activity Index                     9240 non-null   object
 30  Asymmetrique Profile Index                      9240 non-null   object
 31  Asymmetrique Activity Score                     9240 non-null   float64
 32  Asymmetrique Profile Score                      9240 non-null   float64
 33  I agree to pay the amount through cheque        9240 non-null   object
 34  A free copy of Mastering The Interview          9240 non-null   object
 35  Last Notable Activity                           9240 non-null   object
 36  Lead Source_filled                              9240 non-null   object
dtypes: float64(4), int64(3), object(30)
memory usage: 2.6+ MB

## Handling Duplicate Column

In [121]:
data_dropped.loc[data_dropped['Prospect ID'].duplicated()]

Empty DataFrame
Columns: [Prospect ID, Lead Number, Lead Origin, Lead Source, Do Not Email, Do Not Call, Converted, TotalVisits, Total Time Spent on Website, Page Views Per Visit, Last Activity, Country, Specialization, How did you hear about Madugital, What is your current occupation, What matters most to you in choosing a product, Search, Magazine, Newspaper Article, Madugital Telegram, Newspaper, Digital Advertisement, Through Recommendations, Receive More Updates About Our Products, Tags, Update me on Supply Chain Content, Get updates on DM Content, Lead Profile, City, Asymmetrique Activity Index, Asymmetrique Profile Index, Asymmetrique Activity Score, Asymmetrique Profile Score, I agree to pay the amount through cheque, A free copy of Mastering The Interview, Last Notable Activity, Lead Source_filled]
Index: []

[0 rows x 37 columns]

## Finding Data Insight

In [122]:
#agregat data berdasarkan suatu colomn 
data_dropped.groupby('Converted').mean()[['Total Time Spent on Website']]

           Total Time Spent on Website
Converted
0                           330.404473
1                           738.546757

In [123]:
data_dropped.groupby('Converted').mean()[['TotalVisits']]

           TotalVisits
Converted
0             3.317485
1             3.618085

In [124]:
data_dropped.groupby('Asymmetrique Activity Index').mean()[['Asymmetrique Activity Score']]

                             Asymmetrique Activity Score
Asymmetrique Activity Index
01.High                                        16.437272
02.Medium                                      14.273054
03.Low                                         11.290055

In [125]:
data_dropped.groupby('Asymmetrique Profile Index').mean()[['Asymmetrique Profile Score']]

                            Asymmetrique Profile Score
Asymmetrique Profile Index
01.High                                      18.128007
02.Medium                                    16.158864
03.Low                                       11.709677

In [126]:
#menghitung hubungan antara 2 variable
# pd.crosstab(data_dropped['Asymmetrique Activity Index'], data_dropped['Asymmetrique Activity Score']) #hanya menunjukan valuesnya saja (kurang bisa di pahami)
pd.crosstab(data_dropped['Asymmetrique Activity Index'], data_dropped['Asymmetrique Activity Score'],normalize=True)

Asymmetrique Activity Score,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0
Asymmetrique Activity Index,,,,,,,,,,,,
01.High,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.050541,0.037771,0.000541
02.Medium,0.000000,0.000000,0.000000,0.007143,0.012879,0.016017,0.133333,0.351623,0.2671,0.048052,0.035823,0.000000
03.Low,0.000108,0.000433,0.000974,0.006169,0.010281,0.021212,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000

In [127]:
pd.crosstab(data_dropped['Asymmetrique Profile Index'], data_dropped['Asymmetrique Profile Score'], normalize=True)

Asymmetrique Profile Score,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0
Asymmetrique Profile Index,,,,,,,,,,
01.High,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.062662,0.115909,0.026515,0.033333
02.Medium,0.000000,0.001190,0.028355,0.045346,0.294264,0.123268,0.061797,0.125649,0.031277,0.047078
03.Low,0.000974,0.002381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [128]:
pd.crosstab(data_dropped['Converted'], data_dropped['Asymmetrique Activity Index'], normalize=True)

Asymmetrique Activity Index   01.High  02.Medium    03.Low
Converted
0                            0.062338   0.516667  0.035606
1                            0.026515   0.355303  0.003571

In [129]:
pd.crosstab(data_dropped['Converted'], data_dropped['Asymmetrique Profile Index'], normalize=True)

Asymmetrique Profile Index   01.High  02.Medium    03.Low
Converted
0                           0.125325   0.487554  0.001732
1                           0.113095   0.270671  0.001623

# Data manipulation

## Binning

In [132]:
#membagi data numerik sesuai kuantilnya
data_dropped['Deal'] = np.where(data_dropped['Converted'] == 1 , 'YES' , 'NO')

In [133]:
data_dropped.loc[data_dropped['Deal']=='YES']

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity,Lead Source_filled,Deal
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,...,Jakarta,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened,Direct Traffic,YES
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,...,Jakarta,02.Medium,01.High,15.0,18.0,No,No,Modified,Google,YES
6,9fae7df4-169d-489b-afe4-0f3d752542ed,660673,Landing Page Submission,Google,No,No,1,2.0,1640,2.00,...,Jakarta,02.Medium,01.High,14.0,20.0,No,No,Modified,Google,YES
10,2a369e35-ca95-4ca9-9e4f-9d27175aa320,660608,Landing Page Submission,Organic Search,No,No,1,8.0,1351,8.00,...,Other Metro Cities,02.Medium,02.Medium,15.0,14.0,No,Yes,Email Opened,Organic Search,YES
11,9bc8ce93-6144-49e0-9f9d-080fc980f83c,660570,Landing Page Submission,Direct Traffic,No,No,1,8.0,1343,2.67,...,Bodetabek,02.Medium,01.High,14.0,17.0,No,Yes,Page Visited on Website,Direct Traffic,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9233,3f715465-2546-47cd-afa8-8b8dc63b8b43,579622,API,Direct Traffic,No,No,1,13.0,1409,2.60,...,Select,02.Medium,02.Medium,14.0,20.0,No,No,SMS Sent,Direct Traffic,YES
9234,c0b25922-511f-4c56-852e-ced210a45447,579615,Landing Page Submission,Direct Traffic,No,No,1,5.0,210,2.50,...,Jakarta,02.Medium,01.High,14.0,20.0,No,No,Modified,Direct Traffic,YES
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,Jakarta,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam,Direct Traffic,YES
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent,Google,YES
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified,Direct Traffic,YES

In [136]:
data_dropped.sample(5)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity,Lead Source_filled,Deal
6186,dbeb1e99-b6e5-44e5-85d5-67017754e8b7,602359,Landing Page Submission,Direct Traffic,No,No,1,2.0,848,2.0,...,Jakarta,02.Medium,02.Medium,14.0,17.0,No,Yes,Modified,Direct Traffic,YES
8321,7a6fc0c2-6448-4115-b53c-6da807ee760a,586345,API,Olark Chat,No,No,1,0.0,0,0.0,...,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified,Olark Chat,YES
3190,86c1c858-6e3d-407a-a817-91c6fd60bea8,629468,API,Organic Search,No,No,1,4.0,1600,4.0,...,Select,02.Medium,02.Medium,14.0,18.0,No,No,SMS Sent,Organic Search,YES
5112,898fe0e9-7438-49d2-977b-a1cd60d803cf,610781,Landing Page Submission,Direct Traffic,Yes,No,0,4.0,545,2.0,...,Jakarta,02.Medium,02.Medium,14.0,18.0,No,Yes,Page Visited on Website,Direct Traffic,NO
1669,df24a8c0-e4a3-4a30-a729-1462c9fe3c20,643088,Landing Page Submission,Google,Yes,No,0,3.0,1083,3.0,...,Bodetabek,02.Medium,01.High,13.0,17.0,No,Yes,Email Bounced,Google,NO

## Clipping

In [163]:
#membatasi nilai dari 1 - 100
data_dropped['Page Views Per Visit'] = data_dropped['Page Views Per Visit'].clip(1,100)

In [164]:
data_dropped['Page Views Per Visit'].describe()

count    9240.000000
mean        2.592335
std         1.837692
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max        15.000000
Name: Page Views Per Visit, dtype: float64

# Modelling Preparation

In [184]:
data_dropped.columns

Index(['Converted', 'TotalVisits', 'Total Time Spent on Website',
       'Page Views Per Visit', 'Asymmetrique Activity Index',
       'Asymmetrique Profile Index', 'Asymmetrique Activity Score',
       'Asymmetrique Profile Score', 'Deal'],
      dtype='object')

In [183]:
data_dropped = data_droppe.drop(['Prospect ID', 'Lead Number', 'Lead Origin', 'Lead Source',
       'Do Not Email', 'Do Not Call','Last Activity',
       'Country', 'Specialization', 'How did you hear about Madugital',
       'What is your current occupation',
       'What matters most to you in choosing a product', 'Search', 'Magazine',
       'Newspaper Article', 'Madugital Telegram', 'Newspaper',
       'Digital Advertisement', 'Through Recommendations',
       'Receive More Updates About Our Products', 'Tags',
       'Update me on Supply Chain Content', 'Get updates on DM Content',
       'Lead Profile', 'City','I agree to pay the amount through cheque',
       'A free copy of Mastering The Interview', 'Last Notable Activity',
       'Lead Source_filled'],1)

C:\Users\ASUS\AppData\Local\Temp/ipykernel_5660/928179160.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  data_dropped = data_dropped.drop(['Prospect ID', 'Lead Origin', 'Lead Source',

KeyError: "['Prospect ID' 'Lead Origin' 'Lead Source' 'Do Not Email' 'Do Not Call'\n 'Last Activity' 'Country' 'Specialization'\n 'How did you hear about Madugital' 'What is your current occupation'\n 'What matters most to you in choosing a product' 'Search' 'Magazine'\n 'Newspaper Article' 'Madugital Telegram' 'Newspaper'\n 'Digital Advertisement' 'Through Recommendations'\n 'Receive More Updates About Our Products' 'Tags'\n 'Update me on Supply Chain Content' 'Get updates on DM Content'\n 'Lead Profile' 'City' 'I agree to pay the amount through cheque'\n 'A free copy of Mastering The Interview' 'Last Notable Activity'\n 'Lead Source_filled'] not found in axis"

In [170]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(data_dropped, test_size=0.3, random_state=2021)

In [171]:
train.shape, test.shape

((6468, 9), (2772, 9))

# Modelling

In [178]:
train.columns

Index(['Converted', 'TotalVisits', 'Total Time Spent on Website',
       'Page Views Per Visit', 'Asymmetrique Activity Index',
       'Asymmetrique Profile Index', 'Asymmetrique Activity Score',
       'Asymmetrique Profile Score', 'Deal'],
      dtype='object')

In [200]:
from sklearn.linear_model import LinearRegression
# X = prediktor, y = target

X_train =train.drop(['Converted','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)
y_train =train['Converted']
X_test =test.drop(['Converted','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)
y_test =test['Converted']

lr = LinearRegression(normalize=True)
lr.fit(X_train, y_train)

C:\Users\ASUS\AppData\Local\Temp/ipykernel_5660/861940825.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X_train =train.drop(['Converted','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)
C:\Users\ASUS\AppData\Local\Temp/ipykernel_5660/861940825.py:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X_test =test.drop(['Converted','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)

LinearRegression(normalize=True)

In [182]:
X_test[2:3]

,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score
9209,1.0,1226,1.0,14.0,18.0

In [194]:
lr.predict(X_test[2:3])

array([0.69278161])

In [217]:
from sklearn.tree import DecisionTreeClassifier

X_train =train.drop(['TotalVisits','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)
y_train =train['TotalVisits']
X_test =test.drop(['TotalVisits','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)
y_test =test['TotalVisits']

dt= DecisionTreeClassifier(max_depth=10, min_samples_split=5,random_state=2021)
dt.fit(X_train, y_train)

C:\Users\ASUS\AppData\Local\Temp/ipykernel_5660/2278936667.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X_train =train.drop(['TotalVisits','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)
C:\Users\ASUS\AppData\Local\Temp/ipykernel_5660/2278936667.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X_test =test.drop(['TotalVisits','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)

DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=2021)

In [192]:
X_test[2:3]

,Converted,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score
9209,0,1226,1.0,14.0,18.0

In [193]:
dt.predict(X_test[2:3])

array([2.])

In [206]:
from sklearn.cluster import KMeans

X_train = train.drop(['TotalVisits','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)
y_test = test.drop(['TotalVisits','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)

KMeans = KMeans(n_clusters=5, max_iter=100)
KMeans.fit(X_train)

C:\Users\ASUS\AppData\Local\Temp/ipykernel_5660/2005113647.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X_train = train.drop(['TotalVisits','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)
C:\Users\ASUS\AppData\Local\Temp/ipykernel_5660/2005113647.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  y_test = test.drop(['TotalVisits','Deal','Asymmetrique Profile Index', 'Asymmetrique Activity Index'],1)

KMeans(max_iter=100, n_clusters=5)

In [196]:
X_test[2:3]

,Converted,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score
9209,0,1226,1.0,14.0,18.0

In [197]:
KMeans.predict(X_train[2:3])

array([0])

# Data Evaluation

In [198]:
from sklearn.metrics import mean_squared_error, accuracy_score, precision_score, recall_score, silhouette_score

In [201]:
#regresion
y_pred = lr.predict(X_test)
mean_squared_error(y_test, y_pred)

0.1983498794262025

In [220]:
#classification
y_pred = dt.predict(X_test)
acc = accuracy_score(y_test, y_pred)
# prec = precision_score(y_test, y_pred)
#recall = recall_score(y_test, y_pred)
print(acc)

0.8690476190476191

In [216]:
#KMeans / Clustering
silhouette_score(X_train, KMeans.labels_)

0.6314487849691619